source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'LolMate' do
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.3'
    pod 'Hyphenate', '~> 3.3.2'
    pod 'MJRefresh'
    pod 'MWPhotoBrowser', '~> 2.1.2'
    pod 'DACircularProgress', '~> 2.3.1'
    pod 'pop', '~> 1.0'
end