# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Text'), (2, 'Meme')])),
                ('content', models.CharField(max_length=1000)),
                ('like', models.BigIntegerField(default=0)),
                ('dislike', models.BigIntegerField(default=0)),
                ('joke_vec', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Lol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'LOL'), (-1, 'Nah')])),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Joke')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')])),
                ('interested_in', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')])),
            ],
        ),
        migrations.AddField(
            model_name='lol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='joke',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
